/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpacesImport } from './routes/spaces'
import { Route as AuthImport } from './routes/auth'
import { Route as SpacesIndexImport } from './routes/spaces.index'
import { Route as SpacesSpaceidImport } from './routes/spaces.$spaceid'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SpacesRoute = SpacesImport.update({
  path: '/spaces',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SpacesIndexRoute = SpacesIndexImport.update({
  path: '/',
  getParentRoute: () => SpacesRoute,
} as any)

const SpacesSpaceidRoute = SpacesSpaceidImport.update({
  path: '/$spaceid',
  getParentRoute: () => SpacesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/spaces': {
      preLoaderRoute: typeof SpacesImport
      parentRoute: typeof rootRoute
    }
    '/spaces/$spaceid': {
      preLoaderRoute: typeof SpacesSpaceidImport
      parentRoute: typeof SpacesImport
    }
    '/spaces/': {
      preLoaderRoute: typeof SpacesIndexImport
      parentRoute: typeof SpacesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AuthRoute,
  SpacesRoute.addChildren([SpacesSpaceidRoute, SpacesIndexRoute]),
])

/* prettier-ignore-end */
